POST http://localhost:8081/casos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiYXV0aCI6W3siYXV0aG9yaXR5IjoiUk9MRV9DTElFTlQifV0sImlhdCI6MTU4NTMyMjcyMywiZXhwIjoxNTg1MzIzMDIzfQ.fhW0KeW3B8fZW1xzW2n1aQutCHelni-mQBkdg53wgDk
Content-Type: application/json

{
    "acesso": "P",
    "clientes": "teste 1",
    "dataCriacao": "2020-03-27",
    "descricao": "desc 1",
    "observacoes": "obs 1",
    "pasta": "pasta 1",
    "responsavel": "resp 1",
    "titulo": "titulo 1"
}